### ISSUE TITLE
[BUG] Bot Unable to detect flat size

### ISSUE THREAD

**Issue by iTatla1** [Vel-San/wbmbot_v2#4]
**Describe the bug**
Bot ignores the apartment as users set limit is something greater than 0. Bot detects the apartment size as 0 m2 

**To Reproduce**
Run the bot when apartment is available

**Screenshots**
<img width="1591" alt="Screenshot 2024-04-29 at 4 24 11 PM" src="https://github.com/Vel-San/wbmbot_v2/assets/21122013/5fa930e6-9ba2-45f4-8287-5452886eff03">

**Environment**
MAC OS - 14.4.1

**Additional context**
[29.04.2024 - 16:17] [main.py:76] [INFO] Checking for internet connection 🔎
[29.04.2024 - 16:17] [main.py:84] [SUCCESS] Online 🟢
[29.04.2024 - 16:17] [io_operations.py:24] [INFO] Loading WBM config ⚙️
[29.04.2024 - 16:17] [main.py:107] [INFO] Connecting to 'https://www.wbm.de/wohnungen-berlin/angebote/' 🔗
[29.04.2024 - 16:17] [webDriverOperations.py:252] [SUCCESS] Cookies have been accepted 🍪
[29.04.2024 - 16:17] [webDriverOperations.py:380] [INFO] Looking for flats 👀
[29.04.2024 - 16:17] [webDriverOperations.py:387] [SUCCESS] Found 2 flat(s) in total 💡
[29.04.2024 - 16:17] [webDriverOperations.py:438] [WARNING] Ignoring flat '3-ZIMMER WOHNUNG IN MITTE WBS 140' because the size doesn't match our criteria --> Flat Size: 0.0 m² | User wants it above: 40 m² 🙈
[29.04.2024 - 16:17] [webDriverOperations.py:438] [WARNING] Ignoring flat '2-ZIMMER-WOHNUNG IN MITTE WBS 160/180/220' because the size doesn't match our criteria --> Flat Size: 0.0 m² | User wants it above: 40 m² 🙈
[29.04.2024 - 16:17] [webDriverOperations.py:61] [ERROR] Failed to switch page, last page reached ❌
[29.04.2024 - 16:18] [webDriverOperations.py:504] [INFO] Reloading main page 🔄
[29.04.2024 - 16:18] [webDriverOperations.py:380] [INFO] Looking for flats 👀
[29.04.2024 - 16:18] [webDriverOperations.py:387] [SUCCESS] Found 2 flat(s) in total 💡
[29.04.2024 - 16:18] [webDriverOperations.py:438] [WARNING] Ignoring flat '3-ZIMMER WOHNUNG IN MITTE WBS 140' because the size doesn't match our criteria --> Flat Size: 0.0 m² | User wants it above: 40 m² 🙈
[29.04.2024 - 16:18] [webDriverOperations.py:438] [WARNING] Ignoring flat '2-ZIMMER-WOHNUNG IN MITTE WBS 160/180/220' because the size doesn't match our criteria --> Flat Size: 0.0 m² | User wants it above: 40 m² 🙈
[29.04.2024 - 16:18] [webDriverOperations.py:61] [ERROR] Failed to switch page, last page reached ❌
[29.04.2024 - 16:19] [webDriverOperations.py:504] [INFO] Reloading main page 🔄
[29.04.2024 - 16:19] [webDriverOperations.py:380] [INFO] Looking for flats 👀
[29.04.2024 - 16:19] [webDriverOperations.py:387] [SUCCESS] Found 2 flat(s) in total 💡
[29.04.2024 - 16:19] [webDriverOperations.py:438] [WARNING] Ignoring flat '3-ZIMMER WOHNUNG IN MITTE WBS 140' because the size doesn't match our criteria --> Flat Size: 0.0 m² | User wants it above: 40 m² 🙈
[29.04.2024 - 16:19] [webDriverOperations.py:438] [WARNING] Ignoring flat '2-ZIMMER-WOHNUNG IN MITTE WBS 160/180/220' because the size doesn't match our criteria --> Flat Size: 0.0 m² | User wants it above: 40 m² 🙈
[29.04.2024 - 16:20] [webDriverOperations.py:61] [ERROR] Failed to switch page, last page reached ❌
[29.04.2024 - 16:21] [webDriverOperations.py:504] [INFO] Reloading main page 🔄
[29.04.2024 - 16:21] [webDriverOperations.py:380] [INFO] Looking for flats 👀
[29.04.2024 - 16:21] [webDriverOperations.py:387] [SUCCESS] Found 2 flat(s) in total 💡
[29.04.2024 - 16:21] [webDriverOperations.py:438] [WARNING] Ignoring flat '3-ZIMMER WOHNUNG IN MITTE WBS 140' because the size doesn't match our criteria --> Flat Size: 0.0 m² | User wants it above: 40 m² 🙈
[29.04.2024 - 16:21] [webDriverOperations.py:438] [WARNING] Ignoring flat '2-ZIMMER-WOHNUNG IN MITTE WBS 160/180/220' because the size doesn't match our criteria --> Flat Size: 0.0 m² | User wants it above: 40 m² 🙈
[29.04.2024 - 16:21] [webDriverOperations.py:61] [ERROR] Failed to switch page, last page reached ❌
[29.04.2024 - 16:22] [webDriverOperations.py:504] [INFO] Reloading main page 🔄
[29.04.2024 - 16:22] [webDriverOperations.py:380] [INFO] Looking for flats 👀
[29.04.2024 - 16:22] [webDriverOperations.py:387] [SUCCESS] Found 2 flat(s) in total 💡
[29.04.2024 - 16:22] [webDriverOperations.py:438] [WARNING] Ignoring flat '3-ZIMMER WOHNUNG IN MITTE WBS 140' because the size doesn't match our criteria --> Flat Size: 0.0 m² | User wants it above: 40 m² 🙈
[29.04.2024 - 16:22] [webDriverOperations.py:438] [WARNING] Ignoring flat '2-ZIMMER-WOHNUNG IN MITTE WBS 160/180/220' because the size doesn't match our criteria --> Flat Size: 0.0 m² | User wants it above: 40 m² 🙈
[29.04.2024 - 16:22] [webDriverOperations.py:61] [ERROR] Failed to switch page, last page reached ❌
^CTraceback (most recent call last):
  File "/Users/UsmanTatla/Desktop/wbmbot_v2-main/wbmbot_v2/main.py", line 134, in <module>
    main()
  File "/Users/UsmanTatla/Desktop/wbmbot_v2-main/wbmbot_v2/main.py", line 111, in main
    webDriverOperations.process_flats(
  File "/Users/UsmanTatla/Desktop/wbmbot_v2-main/wbmbot_v2/helpers/webDriverOperations.py", line 500, in process_flats
    time.sleep(int(refresh_internal) * 60)
KeyboardInterrupt

UsmanTatla@MacBookPro wbmbot_v2-main %

**Comment by Vel-San** [comment]
@iTatla1 Thanks for reporting this issue.

I've encountered this several times before, and usually it is a problem from the WBM listing itself.

Can you please share your configs as well? Ommit any user identifying credentials or entries please.

Also, try to run it with debug enabled whenever you encounter this issue, verbosity helps me pinpoint the problem.

The "Apartment Description list" array usually has about 12 values, but sometimes the person who publishes the listing forgets to mention one of the entries so the array indexes are messed up, and the bot has a certain order of the indexes, when not properly found, things that there is no size, thus the 0.0m2

I can try to make a workaround for it once I have some free time!

Thanks again :) And goodluck in your hunt!
